server:
  port: 8081
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/commulinic?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
logging:
  level:
    com:
      commulinic:
        mapper: debug
        service: info
        controller: info
mybatis:
  mapper-locations: classpath:mapper/*.xml